@api= http://localhost:3000/usuarios

POST {{api}}
Content-Type: application/json

{
    "username":"usuario2",
    "Password":"usuario2",
    "nombre":"Usuario",
    "ApellidoP":"uno",
    "ApellidoM":"one",
    "Correo":"usuario1@mail.com",
    "rol":2
}
####
GET {{api}}/usuario1
###
POST {{api}}/login
Content-Type: application/json

{
    "username":"usuario1",
    "Password":"usuario1"
}