@api= http://localhost:3000/usuarios
@api2= http://localhost:3000/productos
@api3= http://localhost:3000/pedidos
@api4=http://localhost:3000/ventas
POST {{api}}
Content-Type: application/json

{
    "username":"usuario2",
    "Password":"usuario2",
    "nombre":"Usuario",
    "ApellidoP":"uno",
    "ApellidoM":"one",
    "Correo":"usuario1@mail.com",
    "rol":2
}
####
GET {{api}}/usuario1
###
POST {{api}}/login
Content-Type: application/json

{
    "username":"usuario1",
    "Password":"usuario1"
}
###
GET {{api2}}
###
POST {{api2}}
Content-Type: application/json

{
    "nombre":"Dragon Cake",
    "informacion":"Pastel con un Gran dragon en medio",
    "imagen":"imagen.jpg",
    "precio":50
}
###
GET {{api2}}

###
GET {{api3}}
###
POST {{api3}}
Content-Type: application/json

{
    "codigop":"1234",
    "idproducto":1,
    "cantidad":1,
    "total":1,
    "username":"usuario1",
    "completo":true
}
###
GET {{api3}}/usuario1
###
DELETE {{api3}}/2
###
PUT {{api3}}/7
Content-Type: application/json

{
    "completo":true
}
###
GET {{api3}}/8f5ce545
###
POST {{api4}}
Content-Type: application/json

{
    "codcake":"cc12c8d6-ed40-408d-b58c-188e8b4cb337"
}